import {
  ElAutocomplete,
  ElCascader,
  ElCheckbox,
  ElCheckboxGroup,
  ElColorPicker,
  ElDatePicker,
  ElInput,
  ElInputNumber,
  ElInputOtp,
  ElInputTag,
  ElMention,
  ElRadio,
  ElRadioGroup,
  ElRate,
  ElSegmented,
  ElSelect,
  ElSelectV2,
  ElSlider,
  ElSwitch,
  ElTimePicker,
  ElTimeSelect,
  ElTransfer,
  ElTreeSelect,
} from "element-plus";
import type { Component } from "vue";
import type { ElementPlusFieldName } from "./adapter";

/** Element Plus 字段全量组件，键名统一使用 Schema 的无 El 前缀名称。 */
export const fieldComponents: Record<ElementPlusFieldName, Component> = {
  Input: ElInput,
  InputNumber: ElInputNumber,
  InputOtp: ElInputOtp,
  InputTag: ElInputTag,
  Autocomplete: ElAutocomplete,
  Mention: ElMention,
  Select: ElSelect,
  SelectV2: ElSelectV2,
  Cascader: ElCascader,
  TreeSelect: ElTreeSelect,
  Radio: ElRadio,
  RadioGroup: ElRadioGroup,
  Checkbox: ElCheckbox,
  CheckboxGroup: ElCheckboxGroup,
  Switch: ElSwitch,
  DatePicker: ElDatePicker,
  DateRangePicker: ElDatePicker,
  TimePicker: ElTimePicker,
  TimeRangePicker: ElTimePicker,
  TimeSelect: ElTimeSelect,
  ColorPicker: ElColorPicker,
  Rate: ElRate,
  Slider: ElSlider,
  Segmented: ElSegmented,
  Transfer: ElTransfer,
};
