/**
 * antdv-superform 1.0 的 Ant Design 运行时边界。
 *
 * 业务组件只从此文件导入，避免上游导出调整继续扩散到整个项目。
 * 此边界只面向 antdv-next，不提供 ant-design-vue 3.x 回退。
 */
export {
  AutoComplete,
  Button,
  Card,
  CheckableTag,
  Checkbox,
  CheckboxGroup,
  Col,
  Collapse,
  CollapsePanel,
  ConfigProvider,
  DatePicker,
  DateRangePicker,
  Descriptions,
  DescriptionsItem,
  Divider,
  Dropdown,
  Form,
  FormItem,
  Image,
  Input,
  InputNumber,
  InputSearch,
  Menu,
  MenuItem,
  Modal,
  Radio,
  RadioButton,
  RadioGroup,
  Row,
  Select,
  Slider,
  Space,
  SpaceCompact,
  Spin,
  Switch,
  Table,
  TabPane,
  Tabs,
  Tag,
  TextArea,
  TimePicker,
  TimeRangePicker,
  Tooltip,
  Tree,
  TreeSelect,
  Upload,
  message,
}

export type {
  AutoCompleteProps,
  ButtonProps,
  CheckboxGroupProps,
  ColProps,
  DatePickerProps,
  DescriptionsProps,
  DropdownProps,
  FormInstance,
  FormItemProps,
  FormProps,
  InputNumberProps,
  InputProps,
  PaginationProps,
  RadioGroupProps,
  RangePickerProps,
  RowProps,
  SelectProps,
  SpaceProps,
  SwitchProps,
  TableColumnType,
  TableProps,
  TabsProps,
  TextAreaProps,
  TimePickerProps,
  TimeRangePickerProps,
  TooltipProps,
  TreeSelectProps,
  UploadProps,
} from 'antdv-next'

export type { Locale } from 'antdv-next/dist/locale/index'
export type { ModalFuncProps, ModalProps } from 'antdv-next/dist/modal/interface'
export { useConfig as useAntdvConfig } from 'antdv-next/config-provider/context'

export type BaseComponentName = string
export type BaseComponents = Record<BaseComponentName, any>

const baseComponents: BaseComponents = {
  SpaceCompact,
  Form,
  FormItem,
  Tooltip,
  Button,
  Divider,
  Dropdown,
  Menu,
  MenuItem,
  Space,
  Card,
  Descriptions,
  DescriptionsItem,
  Modal,
  Table,
  Tabs,
  TabPane,
  CollapsePanel,
  Collapse,
  Input,
  InputNumber,
  InputSearch,
  TextArea,
  Select,
  Switch,
  DateRangePicker,
  TimeRangePicker,
  DatePicker,
  TimePicker,
  RadioButton,
  Radio,
  RadioGroup,
  Checkbox,
  CheckboxGroup,
  TreeSelect,
  Row,
  Col,
  Upload,
  Tag,
  CheckableTag,
  AutoComplete,
}

export default baseComponents
import {
  AutoComplete,
  Button,
  Card,
  CheckableTag,
  Checkbox,
  CheckboxGroup,
  Col,
  Collapse,
  CollapsePanel,
  ConfigProvider,
  DatePicker,
  DateRangePicker,
  Descriptions,
  DescriptionsItem,
  Divider,
  Dropdown,
  Form,
  FormItem,
  Image,
  Input,
  InputNumber,
  InputSearch,
  Menu,
  MenuItem,
  Modal,
  Radio,
  RadioButton,
  RadioGroup,
  Row,
  Select,
  Slider,
  Space,
  SpaceCompact,
  Spin,
  Switch,
  Table,
  TabPane,
  Tabs,
  Tag,
  TextArea,
  TimePicker,
  TimeRangePicker,
  Tooltip,
  Tree,
  TreeSelect,
  Upload,
  message,
} from 'antdv-next'
