/** 纯名称目录：供初始化与自动导入共用，不引入 UI 组件。 */
export const antdvFieldNames = [
  'Input',
  'TextArea',
  'InputNumber',
  'InputOTP',
  'InputPassword',
  'InputSearch',
  'AutoComplete',
  'Cascader',
  'ColorPicker',
  'Select',
  'Radio',
  'RadioGroup',
  'Checkbox',
  'CheckboxGroup',
  'DatePicker',
  'DateRangePicker',
  'DateMonthPicker',
  'DateQuarterPicker',
  'DateWeekPicker',
  'DateYearPicker',
  'TimePicker',
  'TimeRangePicker',
  'TreeSelect',
  'Switch',
  'Rate',
  'Mentions',
  'Segmented',
  'Slider',
  'Transfer',
] as const

export type AntdvFieldName = typeof antdvFieldNames[number]
