import {
  AutoComplete,
  Checkbox,
  CheckboxGroup,
  Cascader,
  ColorPicker,
  DateMonthPicker,
  DatePicker,
  DateQuarterPicker,
  DateRangePicker,
  DateWeekPicker,
  DateYearPicker,
  Input,
  InputNumber,
  InputOTP,
  InputPassword,
  InputSearch,
  Mentions,
  Radio,
  RadioGroup,
  Rate,
  Segmented,
  Select,
  Slider,
  Switch,
  TextArea,
  TimePicker,
  TimeRangePicker,
  Transfer,
  TreeSelect,
} from "antdv-next";
import type { Component } from "vue";
import type { AntdvFieldName } from "./adapter";

/** AntDV Adapter 支持的全量字段组件，适合不使用自动导入插件的应用。 */
export const fieldComponents: Record<AntdvFieldName, Component> = {
  Input,
  TextArea,
  InputNumber,
  InputOTP,
  InputPassword,
  InputSearch,
  AutoComplete,
  Cascader,
  ColorPicker,
  Select,
  Radio,
  RadioGroup,
  Checkbox,
  CheckboxGroup,
  DatePicker,
  DateRangePicker,
  DateMonthPicker,
  DateQuarterPicker,
  DateWeekPicker,
  DateYearPicker,
  TimePicker,
  TimeRangePicker,
  TreeSelect,
  Switch,
  Rate,
  Mentions,
  Segmented,
  Slider,
  Transfer,
};
